name: Build and Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Using a more recent LTS version
        registry-url: 'https://registry.npmjs.org'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v2
      with:
        diff-search: true
        file-name: package.json
        file-url: https://unpkg.com/rdscom/package.json
        static-checking: localIsNew

    - name: Publish to npm
      if: steps.check.outputs.changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}